//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersBook_WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pupils
    {
        public System.Guid id { get; set; }
        public string nickName { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string adress { get; set; }
        public Nullable<int> postalCode { get; set; }
        public string city { get; set; }
        public System.Guid @class { get; set; }
    
        public virtual Classes Classes { get; set; }
    }
}
