//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersBook_WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectToTimeTableHours
    {
        public System.Guid timetableId { get; set; }
        public Nullable<System.Guid> subjectId { get; set; }
        public Nullable<System.Guid> breakId { get; set; }
    
        public virtual Breaks Breaks { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual TimeTableIItems TimeTableIItems { get; set; }
    }
}
