//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersBook_WebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeachersBookEntities2 : DbContext
    {
        public TeachersBookEntities2()
            : base("name=TeachersBookEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Breaks> Breaks { get; set; }
        public virtual DbSet<Lists> Lists { get; set; }
        public virtual DbSet<Pupils> Pupils { get; set; }
        public virtual DbSet<Ratings> Ratings { get; set; }
        public virtual DbSet<SchoolYears> SchoolYears { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<TimeTableIItems> TimeTableIItems { get; set; }
        public virtual DbSet<TimeTableRows> TimeTableRows { get; set; }
        public virtual DbSet<TimeTables> TimeTables { get; set; }
        public virtual DbSet<UserData> UserData { get; set; }
        public virtual DbSet<SubjectToTimeTableHours> SubjectToTimeTableHours { get; set; }
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
