//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersBook_WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTableSubjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeTableSubjects()
        {
            this.TimeTableRows = new HashSet<TimeTableRows>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> mon { get; set; }
        public Nullable<System.Guid> tue { get; set; }
        public Nullable<System.Guid> wed { get; set; }
        public Nullable<System.Guid> thu { get; set; }
        public Nullable<System.Guid> fri { get; set; }
        public Nullable<System.Guid> sat { get; set; }
    
        public virtual Subjects Subjects { get; set; }
        public virtual Subjects Subjects1 { get; set; }
        public virtual Subjects Subjects2 { get; set; }
        public virtual Subjects Subjects3 { get; set; }
        public virtual Subjects Subjects4 { get; set; }
        public virtual Subjects Subjects5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTableRows> TimeTableRows { get; set; }
    }
}
