//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersBook_WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTableRows
    {
        public System.Guid id { get; set; }
        public System.Guid timeTable { get; set; }
        public string rowType { get; set; }
        public int lessonNo { get; set; }
        public Nullable<System.Guid> timeTableSubjects { get; set; }
        public Nullable<System.Guid> timeTableBreaks { get; set; }
        public string time { get; set; }
    
        public virtual TimeTableBreaks TimeTableBreaks1 { get; set; }
        public virtual TimeTables TimeTables { get; set; }
        public virtual TimeTableSubjects TimeTableSubjects1 { get; set; }
    }
}
