//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersBook_WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTableIItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeTableIItems()
        {
            this.TimeTableRows = new HashSet<TimeTableRows>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<int> day { get; set; }
        public string type { get; set; }
        public string description { get; set; }
    
        public virtual SubjectToTimeTableHours SubjectToTimeTableHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTableRows> TimeTableRows { get; set; }
    }
}
