//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersBook_WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTableRows
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeTableRows()
        {
            this.TimeTableIItems = new HashSet<TimeTableIItems>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> timetable { get; set; }
        public string start { get; set; }
        public string end { get; set; }
        public Nullable<int> rowNo { get; set; }
    
        public virtual TimeTables TimeTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTableIItems> TimeTableIItems { get; set; }
    }
}
